sudo: required
services:
    - docker
script:
    - docker build . -t arch
    - docker run  -v $(pwd):/home/docker/build arch -c "yay -S --nodiffmenu --nocleanmenu --noconfirm \
        nerd-fonts-inconsolata-go \
        texlive-most \
        inkscape;
        make"
